import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useChatState } from "@/state/store";

export function DashboardPage() {
  const { totals, items } = useChatState();
  const userMessages = items.filter((i) => i.kind === "user").length;

  return (
    <div className="h-full overflow-y-auto px-6 py-6">
      <h1 className="mb-1 text-lg font-semibold">Dashboard</h1>
      <p className="mb-6 text-sm text-muted-foreground">
        Local session summary. Charts and historical data will land here once Langfuse is wired up.
      </p>
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <Stat title="Turns" value={totals.turns} description="Completed assistant turns" />
        <Stat title="User messages" value={userMessages} description="Sent this session" />
        <Stat title="Input tokens" value={totals.inputTokens.toLocaleString()} description="Charged to context" />
        <Stat title="Output tokens" value={totals.outputTokens.toLocaleString()} description="Generated by model" />
      </div>
    </div>
  );
}

function Stat({ title, value, description }: { title: string; value: string | number; description: string }) {
  return (
    <Card>
      <CardHeader className="pb-2">
        <CardDescription>{title}</CardDescription>
        <CardTitle className="text-2xl tabular-nums">{value}</CardTitle>
      </CardHeader>
      <CardContent className="text-xs text-muted-foreground">{description}</CardContent>
    </Card>
  );
}
